import { motion } from "framer-motion";
import { AnimatedCounter } from "@/components/AnimatedCounter";

const cards = [
  {
    heading: "Why We Built The Enterprise Division",
    body: "Our Trust operates primary healthcare and educational initiatives across UP. To fund these infinitely, without donor fatigue, we established our six for-profit verticals. They compete on merit and fund our mission directly.",
    span: "",
  },
  {
    heading: "A Dual-Powered Mission",
    body: "Our primary healthcare and educational initiatives are supported by two strong pillars: the generous donations of our community backbone, and the market rate profits generated by our enterprise divisions. This hybrid model ensures ultimate sustainability for our impact across Uttar Pradesh.",
    span: "",
  },
  {
    heading: "Operational Supremacy",
    body: "We operate out of Lucknow and Deoria, managing teams of engineers, technicians, and project managers. We do not ask for charity contracts. We bid for enterprise RFPs, and we win on technical specifications.",
    span: "md:col-span-2",
  },
];

const metrics = [
  { label: "Villages Supported", value: 120, prefix: "", suffix: "+" },
  { label: "Solar Commissioned", value: 45, prefix: "", suffix: " MW" },
  { label: "Enterprise Clients", value: 300, prefix: "", suffix: "+" },
  { label: "Profits Retained in UP", value: 100, prefix: "", suffix: "%" },
];

function About() {
  return (
    <div className="container mx-auto px-4 pt-28 pb-16 md:pt-32">
      {/* ── Hero ───────────────────────────────────────────────── */}
      <motion.div
        initial={{ opacity: 0, y: 24 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, ease: "easeOut" }}
        className="mx-auto max-w-3xl text-center"
      >
        <h1 className="text-4xl font-bold tracking-tight text-india-navy drop-shadow-[0_2px_2px_rgba(0,0,0,0.25)] sm:text-5xl lg:text-6xl">
          The Philosophy of{" "}
          <span className="text-india-gradient">Self-Funded Philanthropy</span>
        </h1>
        <p className="mt-5 text-base text-muted-foreground sm:text-lg">
          Rao Sewa Nyas is built on a single, uncompromising principle:
          sustainable community impact cannot rely on donations. It requires
          corporate execution.
        </p>
      </motion.div>

      {/* ── Content Grid ───────────────────────────────────────── */}
      <div className="mx-auto mt-14 grid max-w-5xl grid-cols-1 gap-8 md:grid-cols-2">
        {cards.map((card, index) => (
          <motion.div
            key={card.heading}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.15 + index * 0.1 }}
            className={`glass-card rounded-2xl p-6 transition-transform hover:-translate-y-1 sm:p-8 ${card.span}`}
          >
            <h2 className="text-lg font-semibold text-india-navy sm:text-xl">
              {card.heading}
            </h2>
            <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
              {card.body}
            </p>
          </motion.div>
        ))}
      </div>

      {/* ── Impact Metrics ─────────────────────────────────────── */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true, margin: "-100px" }}
        transition={{ duration: 0.6 }}
        className="mx-auto mt-24 max-w-5xl rounded-[2rem] bg-india-navy/5 p-8 sm:p-12"
      >
        <div className="grid grid-cols-2 gap-8 md:grid-cols-4">
          {metrics.map((metric, index) => (
            <div key={metric.label} className="text-center">
              <div className="text-3xl font-bold tracking-tight text-india-navy sm:text-4xl lg:text-5xl">
                <AnimatedCounter
                  value={metric.value}
                  prefix={metric.prefix}
                  suffix={metric.suffix}
                />
              </div>
              <div className="mt-2 text-sm font-medium text-muted-foreground">
                {metric.label}
              </div>
            </div>
          ))}
        </div>
      </motion.div>
    </div>
  );
}

export default About;
